sudo: required
dist: bionic

language: csharp
mono: none
dotnet: 2.2.105

global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

script:
  - dotnet restore
  - dotnet build

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: 
    - MarsRover.dll
  skip_cleanup: true
  on:
    repo: microgenius/MarsRoverChallenge
    branch: master
    tags: true